- Maui.DataGrid/DataGridRow.cs
- Maui.DataGrid/Utils/LayoutOptionsExtensions.cs
Remove some unnecessary nesting on every row.
> simplify rows

- Maui.DataGrid/BoolToSelectionModeConverter.cs
- Maui.DataGrid/DataGrid.xaml
- Maui.DataGrid/DataGridRow.cs
> Bind SelectionEnabled

- Maui.DataGrid/DataGrid.xaml.cs
consistently unsubscribe from events
> Cleanup events

- Maui.DataGrid/DataGrid.xaml.cs
Don't call IndexOf() multiple times in a row unnecessarily.
> optimize index lookups

- Maui.DataGrid/DataGrid.xaml.cs
As you requested in your other code review
> Prevent item selection logic from executing if SelectionEnabled is false

- Maui.DataGrid/DataGrid.xaml
- Maui.DataGrid/DataGrid.xaml.cs
Also adds a property, RefreshingEnabled
Fixes one part of https://github.com/akgulebubekir/Maui.DataGrid/issues/13
> Bind PullToRefreshCommand and IsRefreshing

- Maui.DataGrid.Sample/MainPage.xaml
- Maui.DataGrid.Sample/ViewModels/MainViewModel.cs
- Maui.DataGrid/DataGrid.xaml
- Maui.DataGrid/DataGrid.xaml.cs
- Maui.DataGrid/DataGridColumn.cs
- Maui.DataGrid/DataGridRow.cs
retry of https://github.com/akgulebubekir/Maui.DataGrid/pull/6 with dynamic width adjustment
> add IsVisible property to columns

- Maui.DataGrid/DataGrid.xaml.cs
- Maui.DataGrid/DataGridRow.cs
These might not matter so much, but don't hurt
> Minor optimizations

- Maui.DataGrid.Sample/MainPage.xaml.cs
- Maui.DataGrid/DataGrid.xaml.cs
- Maui.DataGrid/DataGridColumn.cs
- Maui.DataGrid/Maui.DataGrid.csproj
- Maui.DataGrid/SortData.cs
- Maui.DataGrid/SortDataTypeConverter.cs
- Maui.DataGrid/Utils/ReflectionUtils.cs
Nullable types are great. Helps prevent null dereferences, and ensures the assumptions in the logic are made more explicit and enforceable.
> Nullable types

- Maui.DataGrid/DataGrid.xaml.cs
- Maui.DataGrid/SortData.cs
This fixes the messages and warnings in visual studio
> fix warnings

- .editorconfig
- Maui.DataGrid.Sample/App.xaml.cs
- Maui.DataGrid.Sample/AppShell.xaml.cs
- Maui.DataGrid.Sample/MainPage.xaml.cs
- Maui.DataGrid.Sample/MauiProgram.cs
- Maui.DataGrid.Sample/Models/Team.cs
- Maui.DataGrid.Sample/Platforms/Android/MainActivity.cs
- Maui.DataGrid.Sample/Platforms/Android/MainApplication.cs
- Maui.DataGrid.Sample/Platforms/MacCatalyst/AppDelegate.cs
- Maui.DataGrid.Sample/Platforms/MacCatalyst/Program.cs
- Maui.DataGrid.Sample/Platforms/Tizen/Main.cs
- Maui.DataGrid.Sample/Platforms/Windows/App.xaml.cs
- Maui.DataGrid.Sample/Platforms/iOS/AppDelegate.cs
- Maui.DataGrid.Sample/Platforms/iOS/Program.cs
- Maui.DataGrid.Sample/Utils/DummyDataProvider.cs
- Maui.DataGrid.Sample/ViewModels/MainViewModel.cs
- Maui.DataGrid/BoolToSelectionModeConverter.cs
- Maui.DataGrid/DataGrid.xaml.cs
- Maui.DataGrid/DataGridColumn.cs
- Maui.DataGrid/DataGridRow.cs
- Maui.DataGrid/PaletteCollection.cs
- Maui.DataGrid/Platforms/Android/PlatformClass.cs
- Maui.DataGrid/Platforms/MacCatalyst/PlatformClass.cs
- Maui.DataGrid/Platforms/Tizen/PlatformClass1.cs
- Maui.DataGrid/Platforms/Windows/PlatformClass.cs
- Maui.DataGrid/Platforms/iOS/PlatformClass.cs
- Maui.DataGrid/SortData.cs
- Maui.DataGrid/SortDataTypeConverter.cs
- Maui.DataGrid/Utils/LayoutOptionsExtensions.cs
- Maui.DataGrid/Utils/ReflectionUtils.cs
Minor performance improvement
https://github.com/akgulebubekir/Maui.DataGrid/issues/50
> Make more classes sealed

- Maui.DataGrid/DataGridRow.cs
Fix https://github.com/akgulebubekir/Maui.DataGrid/issues/55
> Fix Issue #55

- Maui.DataGrid.Sample/MainPage.xaml
- Maui.DataGrid.Sample/MainPage.xaml.cs
- Maui.DataGrid/DataGrid.xaml.cs
- Maui.DataGrid/DataGridColumn.cs
- Maui.DataGrid/DataGridRow.cs
This allows dynamically adding or removing columns via code.
Fixes https://github.com/akgulebubekir/Maui.DataGrid/issues/70
> Dynamic columns

- Maui.DataGrid/DataGrid.xaml.cs
Fixes https://github.com/akgulebubekir/Maui.DataGrid/issues/72
> Fix for multiple DataGrids on Android

- Maui.DataGrid/Utils/ReflectionUtils.cs
Some optimizations for sorting
> Optimize Reflection

- Maui.DataGrid/DataGrid.xaml
- Maui.DataGrid/DataGrid.xaml.cs
https://github.com/akgulebubekir/Maui.DataGrid/issues/84
> Added workaround for iOS

- Maui.DataGrid.Sample/MainPage.xaml
- Maui.DataGrid/DataGrid.xaml
- Maui.DataGrid/DataGrid.xaml.cs
Take a look at these changes and see what you think.
Closes https://github.com/akgulebubekir/Maui.DataGrid/issues/69
> Add pagination feature

- Maui.DataGrid.Sample/MainPage.xaml
- Maui.DataGrid.Sample/ViewModels/MainViewModel.cs
- Maui.DataGrid/DataGrid.xaml.cs
Fixes https://github.com/akgulebubekir/Maui.DataGrid/issues/95
> Dynamic Pagination

- Maui.DataGrid/DataGrid.xaml
- Maui.DataGrid/DataGrid.xaml.cs
This is to fix  https://github.com/akgulebubekir/Maui.DataGrid/issues/111
> Fix sorting issue #111

- Maui.DataGrid/Utils/ReflectionUtils.cs
This should help allow less reflection, and will be fully thread-safe.
> Further Optimize Reflection

- Maui.DataGrid/Maui.DataGrid.csproj
> Reproducible builds

- Maui.DataGrid/CompatibilitySuppressions.xml
- Maui.DataGrid/Maui.DataGrid.csproj
> Add package validation

- Maui.DataGrid.Sample/MainPage.xaml
- Maui.DataGrid/CompatibilitySuppressions.xml
- Maui.DataGrid/DataGrid.xaml
- Maui.DataGrid/DataGrid.xaml.cs
> Allow custom PageSizeList and always show PageSize

- Maui.DataGrid/CompatibilitySuppressions.xml
- Maui.DataGrid/DataGrid.xaml
- Maui.DataGrid/DataGrid.xaml.cs
> Expose PaginationStepperStyle as BindableProperty

- Maui.DataGrid/DataGridColumn.cs
- Maui.DataGrid/DataGridRow.cs
> auto detect data type for default edit template

- Maui.DataGrid/DataGrid.xaml.cs
This should fix https://github.com/akgulebubekir/Maui.DataGrid/issues/159
> fix pagination bug

- Maui.DataGrid.Sample/MainPage.xaml
- Maui.DataGrid.Sample/ViewModels/MainViewModel.cs
- Maui.DataGrid/CompatibilitySuppressions.xml
- Maui.DataGrid/DataGrid.xaml
- Maui.DataGrid/DataGrid.xaml.cs
We sometimes perform actions when a row is tapped, even when selection is disabled. To achieve this, I added a GestureRecognizer to the row and set up a bindable command.
> Added Row Tapped capability to bind a Command that gets executed if a row is tapped.

- Maui.DataGrid/DataGrid.xaml
> Fix scrolling issue
