Maui.DataGrid/DataGridRow.cs
Maui.DataGrid/DataGridRowTemplateSelector.cs
Maui.DataGrid/Utils/DataTemplateExtensions.cs

This improves scrolling and prevents an exception on Windows when loading lots of items and then navigating.
The exception this prevents says: "A cycle occurred while laying out the GUI."

Fix exception and prevent recalculations if not needed

---

Maui.DataGrid/DataGridRow.cs

The existing overridden OnBindingContextChanged event handler executes the same UpdateBackgroundColor() method as the propertyChanged delegate of the RowContext property.
No need for this duplication. The BindingContext of the DataGridRow *is* the RowContext.

use BindingContext instead of RowContext

---

Maui.DataGrid/DataGridColumn.cs
Maui.DataGrid/DataGridRow.cs

Self-explanatory. Could be a good prep for allowing to bind on ItemSizingStrategy, which can affect performance, but also can help ensure consistency. If you set WordWrap to off then you can ensure all rows are the same height.
But with variable-height rows, you cannot increase performance that way.

Bind LineBreakMode to DataGridColumn

---

Maui.DataGrid/DataGrid.xaml

The Grid control provides a lot of bindable properties like ColumnDefinitions, RowDefinitions, ColumnSpacing, RowSpacing which could mislead a user, since the API doesn't respect those in a way that would make sense for a user.

use a ContentView to wrap everything

---

Maui.DataGrid/DataGrid.xaml.cs

These are some minor helpful changes.
Refreshing is actually still always showing the indicator for me on Windows, despite that these changes seem like they should work. The PullToRefreshCommand will not execute if RefreshingEnabled is false, but the indicator makes it seem like it is.
Can't use IsEnabled on the RefreshView since that would disable everything inside of it, so I removed those line, and none of the other bindable properties on the RefreshView seem promising.
Changing the default RefreshingEnabled value to false also does nothing
Thoughts? The useless indicator was always active before, so there was no regression on this at any point. But it would be nice to fix it.
Possibly a bug in MAUI itself. The animation should respect the canExecute command.

don't attach or invoke refreshing events if refreshing not enabled

---

Maui.DataGrid/DataGrid.xaml.cs
Maui.DataGrid/DataGridColumn.cs

Can only do sorting via reflection if the type of the column implements IComparable. So this PR uses reflection to determine if this is the case, and caches the result.
Biggest change is that I moved where the header initialization happens, because it needs access to the ItemsSource to generate the header with the current approach of constructing the sorting icons with the gesture recognizers

Prevent sorting on non-sortable columns

---

.editorconfig
Maui.DataGrid.Sample/App.xaml.cs
Maui.DataGrid.Sample/AppShell.xaml.cs
Maui.DataGrid.Sample/MainPage.xaml.cs
Maui.DataGrid.Sample/MauiProgram.cs
Maui.DataGrid.Sample/Models/Team.cs
Maui.DataGrid.Sample/Platforms/Android/MainActivity.cs
Maui.DataGrid.Sample/Platforms/Android/MainApplication.cs
Maui.DataGrid.Sample/Platforms/MacCatalyst/AppDelegate.cs
Maui.DataGrid.Sample/Platforms/MacCatalyst/Program.cs
Maui.DataGrid.Sample/Platforms/Tizen/Main.cs
Maui.DataGrid.Sample/Platforms/Windows/App.xaml.cs
Maui.DataGrid.Sample/Platforms/iOS/AppDelegate.cs
Maui.DataGrid.Sample/Platforms/iOS/Program.cs
Maui.DataGrid.Sample/Utils/DummyDataProvider.cs
Maui.DataGrid.Sample/ViewModels/MainViewModel.cs
Maui.DataGrid/BoolToSelectionModeConverter.cs
Maui.DataGrid/DataGrid.xaml.cs
Maui.DataGrid/DataGridColumn.cs
Maui.DataGrid/DataGridRow.cs
Maui.DataGrid/PaletteCollection.cs
Maui.DataGrid/Platforms/Android/PlatformClass.cs
Maui.DataGrid/Platforms/MacCatalyst/PlatformClass.cs
Maui.DataGrid/Platforms/Tizen/PlatformClass1.cs
Maui.DataGrid/Platforms/Windows/PlatformClass.cs
Maui.DataGrid/Platforms/iOS/PlatformClass.cs
Maui.DataGrid/SortData.cs
Maui.DataGrid/SortDataTypeConverter.cs
Maui.DataGrid/Utils/LayoutOptionsExtensions.cs
Maui.DataGrid/Utils/ReflectionUtils.cs

This adds the .editorconfig file from [this repository](https://github.com/RehanSaeed/EditorConfig). EditorConfig helps align coding styles, using IDE-based enforcement, to ensure consistency and cleaner diffs.
This editorconfig file closely matches the official StyleCop rules. Interestingly, a lot of community conventions within C# are different from what StyleCop recommends. But every rule has some logic behind it.
For instance, requiring the use of "this" ensures that it is always explicit whether you are working with an instance variable, and then makes underscore prefixes redundant. Takes a second to get used to, but of course the rules are configurable.
I used automatic solution-wide refactorings to achieve this PR, and tested that it works with the sample project.
I will make …

EditorConfig

---

Maui.DataGrid.Sample/Maui.DataGrid.Sample.csproj
Maui.DataGrid.Sample/Utils/DummyDataProvider.cs

STJ is faster, and officially supported by Microsoft. Newtonsoft was out of date anyways, and it is one less nuget package that we will need to worry about.
And James Newton-King himself was assimilated by the Microsoft borg anyways.

switch to System.Text.Json in the sample project

---

.editorconfig
Maui.DataGrid.Sample.sln
Maui.DataGrid.Sample/App.xaml.cs
Maui.DataGrid.Sample/AppShell.xaml.cs
Maui.DataGrid.Sample/MainPage.xaml.cs
Maui.DataGrid.Sample/Models/Team.cs
Maui.DataGrid.Sample/Platforms/Windows/App.xaml.cs
Maui.DataGrid.Sample/ViewModels/MainViewModel.cs
Maui.DataGrid/DataGrid.xaml.cs
Maui.DataGrid/DataGridColumn.cs
Maui.DataGrid/DataGridRow.cs
Maui.DataGrid/PaletteCollection.cs
Maui.DataGrid/SortData.cs

This reverses the EditorConfig rules for member qualification, underscore prefixes on fields, and expression-bodied members.

EditorConfig alignment

---

Maui.DataGrid/DataGrid.xaml
Maui.DataGrid/DataGrid.xaml.cs

I feel confident that I placed it on elements that are safe to do this for, but it is still possible that it could be safely placed on other elements later.
See the issue for more explanation of the logic and caveats.
Fix https://github.com/akgulebubekir/Maui.DataGrid/issues/49

Set CompressedLayout.IsHeadless where possible

---

Maui.DataGrid/DataGridRow.cs

Every row was being calculated twice, because CreateView was called inside the OnBindingContextChanged event as well as the propertyChanged event of the DataGrid property.
However, since the bindable property for the DataGrid in the DataGridRow is meant to be a direct reference, bound only one time, and not exposed as part of the API, we don't have to worry about the property ever being updated.

Important performance improvement

---

Maui.DataGrid/DataGrid.xaml

Was able to hardcode this as MeasureFirstItem everywhere except for Android, because of [this bug](https://github.com/dotnet/maui/issues/7562)
Fixes https://github.com/akgulebubekir/Maui.DataGrid/issues/75

Improve performance by setting ItemSizingStrategy

---

Maui.DataGrid/DataGrid.xaml

Use x:DataType to ensure compiled XAML bindings, and improve IntelliSense within the XAML

Use compiled bindings

---

Maui.DataGrid/DataGrid.xaml.cs
Maui.DataGrid/DataGridRow.cs

This should ensure that the colors are only set once during the initialization of the views in the row.
And two other minor changes.

Set colors less

---

Maui.DataGrid/DataGrid.xaml.cs
Maui.DataGrid/DataGridColumn.cs
Maui.DataGrid/DataGridRow.cs

Bindings in collection views are expensive, and we are reloading the entire data grid anyways whenever the IsVisible property changes. So we can just check that property instead of binding on it.

Reduce bindings

---

Maui.DataGrid/DataGrid.xaml

Disable the ability to pull to refresh if the `RefreshingEnabled` property is false.
Fixes https://github.com/akgulebubekir/Maui.DataGrid/issues/88

Disable refresh view when refreshing is disabled

---

Maui.DataGrid/DataGrid.xaml.cs

Thanks for your previous help with issue #100 
Now in my case, I've set the BorderColor in the `Styles.xaml` default file. But it will crash the app because when initialising the component and styling it using implicitly (i.e. not using `Key` and only use `TargetType`), `_headerView` is still null. Since there's a precedent for a null check in`HeaderBackgroundProperty`, I've added a similar null check in `BorderColorProperty`. While I'm at it, I double-checked for other properties that requires null check, but I don't think so since a lot of them should be set after the components have been initialised anyway such as `self._refreshView`, not for styling.
Again, I'm still new with Maui in general, this is my first open-source PR, so I don't know what's the best practice here and if there's …

Fix border color property if set in Styles.xaml

---

Maui.DataGrid/DataGrid.xaml.cs
Maui.DataGrid/DataGridColumn.cs
Maui.DataGrid/DataGridRow.cs
Maui.DataGrid/Extensions/BindablePropertyExtensions.cs

What do you think about this?
To me, all the many bindable properties are the most confusing and intimidating part of trying to modify this library. This approach means less redundant boilerplate and less casting. With this approach, when creating the lambda delegates for the events, the oldValue and newValue will have the appropriate type already. Which also makes it clearer what is happening.
It would cause a slight imperceptible performance degradation in terms of instantiating the data grid, because it is using reflection. And while it simplifies the code elsewhere, it is new code to maintain. On net, it adds code.
This kind of thing would ideally be incorporated into MAUI itself, and I [made a feature suggestion](https://github.com/dotnet/maui/discussions/16302) there.
This approach …

simplify BindableProperty creation

---

Maui.DataGrid/DataGridRow.cs

I noticed XAML binding errors at runtime, which means that the DataGrid was loading all the DataGrid rows twice. Once at first with the BindingContext of the parent DataGrid, and then once for the row.
That first load was completely wrong. This check should reduce runtime errors and cut in half the amount of view creation, while still preserving the ability to change the BindingContext.
But, it would eliminate one possible option, where one has an infinitely recursive ViewModel. That probably would always be wrong, anyways.

Fix binding errors

---

Maui.DataGrid.Sample/MainPage.xaml
Maui.DataGrid.Sample/Maui.DataGrid.Sample.csproj
Maui.DataGrid.Sample/ViewModels/MainViewModel.cs
Maui.DataGrid/DataGrid.xaml
Maui.DataGrid/DataGrid.xaml.cs
Maui.DataGrid/DataGridColumn.cs
Maui.DataGrid/DataGridRow.cs

This adds a RowToEdit property to the DataGrid and an EditCellTemplate property on each column.
This also updates the sample to show how one might be able to take advantage of it.
It currently only supports editing one row at a time. Multiple edit mode could be added in the future.
With the regular CellTemplate, by default a label is used, when no CellTemplate is defined. Similarly, by default, an Entry control is used, when no EditCellTemplate is defined. 
Fixes https://github.com/akgulebubekir/Maui.DataGrid/issues/135

Add ability to do modal inline editing, MVVM-style

---

Maui.DataGrid/DataGrid.xaml.cs
Maui.DataGrid/DataGridRow.cs

This logic allows us to not clear the columns every time, for performance

Don't clear columns every time

---

Maui.DataGrid/DataGrid.xaml.cs
Maui.DataGrid/DataGridRow.cs
Maui.DataGrid/ObservableRangeCollection.cs

This avoids mutating the InternalItems, reduces allocations, and no longer requires that the InternalItems be nullable.

Use ObservableRangeCollection from MvvmHelpers to reduce allocations

---

Maui.DataGrid/DataGrid.xaml

The `PaginationStepperStyle` binding in `DataGrid.xaml` is causing a runtime error because it is set to `StaticResource` and no style with that key exists.
This PR updates the binding to use the bindable property in the `DataGrid` class.

Change PaginationStepperStyle binding to self ref

---

Maui.DataGrid.Sample/MainPage.xaml
Maui.DataGrid.Sample/Resources/Styles/Colors.xaml
Maui.DataGrid.Sample/SettingsPopup.xaml
Maui.DataGrid.Sample/ViewModels/MainViewModel.cs
Maui.DataGrid.Sample/ViewModels/ViewModelBase.cs
Maui.DataGrid/DataGrid.xaml
Maui.DataGrid/DataGrid.xaml.cs
Maui.DataGrid/DataGridCell.cs
Maui.DataGrid/DataGridColumn.cs
Maui.DataGrid/DataGridRow.cs
Maui.DataGrid/Extensions/ListExtensions.cs

The original way that the grid worked involved creating borders between cells by creating empty space, and then using the background color as the border color. That approach is quite counter-intuitive. 
This PR wraps all of the cells with their own border. Now everything is way easier to understand for both users and developers.
UPDATE: This branch is not entirely awful now. It scrolls pretty fast. It is a bit slower is on column reordering and column resizing with large numbers of records. But the main branch isn't great in that scenario either.
Fixes #120

Make the layout sensible

---

Maui.DataGrid/DataGrid.xaml.cs

The Reload method gets called approximately five times, but always before the DataGrid is loaded. As a result, some events were not initialized correctly. In the provided example project, the WonColumnVisible did not trigger an update. It was only after a ColumnChangeEvent (for instance, when a column was added or removed) that the Reload method was executed, and from that point on, the WonColumnVisible behavior started working as expected.

call Reload after DataGrid Loaded to fix initialization

---

Maui.DataGrid/DataGridRow.cs

This is kind of unfortunate because an optimization that used to work is not working anymore. But it might be only of trivial importance compared to whatever virtualization is happening on the CollectionView.
Handling virtualization optimally is a potential TODO item, so I marked that in the comments.
Fixes #166 and #170

Fix sorting with 8.0.6+

---

Maui.DataGrid.Sample/MainPage.xaml
Maui.DataGrid/DataGrid.xaml

Fixes #200 
This isn't a great fix in that this library is still not trimming and aot compatible, but this gets it to at least not-crash in client builds. This library was already incompatible for trimming and aot as x:Object previously just forced reflection bindings anyways in .NET 8.

Fix crash on .NET 9

---

Directory.Build.props

I recently turned on lots of warnings to help ensure readability, code quality, and consistency. I fixed the uncontroversial warnings.
In this PR, the controversial warnings from before I am silencing, which should preserve most of the original stylistic feeling.
These are: [SA1101](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1101.md), [SA1124](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1124.md), and [SA1309](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1309.md)
The general concept behind SA1101 and SA1309, as described, is to make it explicit that you are calling a method of a particular instance, and that you are covertly passing "this" to non-static methods. It also allows …

Silence StyleCop warnings

---

Maui.DataGrid.Sample/packages.lock.json
Maui.DataGrid/DataGrid.xaml
Maui.DataGrid/DataGrid.xaml.cs
Maui.DataGrid/packages.lock.json

Duplicate of https://github.com/akgulebubekir/Maui.DataGrid/pull/206 because that was accidentally closed.
The referenced issue is solved: https://github.com/dotnet/maui/issues/7562
MeasureFirstItem should allow better performance, and for a data grid it makes sense that it should be the default since you will almost always want every row to be the same height.

set MeasureFirstItem as default

---

Maui.DataGrid.Sample/MainPage.xaml
Maui.DataGrid.Sample/ViewModels/MainViewModel.cs
Maui.DataGrid/DataGrid.xaml
Maui.DataGrid/DataGrid.xaml.cs

- Added support for localization of the pagination text (e.g. "Page" and "# per page") in the DataGrid.
- Introduced new properties to allow developers to customize these labels for different languages.
- Tested using the sample project to ensure changes work smoothly with the pagination system.
-------------------------------------
**Notes**: This is my first contribution to a open source project. If there's anything i could improve or if any adjustments are needed, please let me know!

Add localization support for pagination and # per page customization

---

Maui.DataGrid.Sample/Maui.DataGrid.Sample.csproj
Maui.DataGrid.Sample/Properties/launchSettings.json
Maui.DataGrid.Sample/packages.lock.json

To directly run/debug the sample on Windows, I needed to make changes to the launch settings (change to `"commandName": "Project",`) and add an element to the project settings (`<WindowsPackageType>None</WindowsPackageType>`).
The package lock settings regenerated when the launch settings were changed.

Running sample on Windows
